name: poke_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.1.1
  connectivity_plus: ^2.3.9
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^1.0.0
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  liquid_swipe: ^3.0.0
  lottie: ^1.4.3
  page_transition: ^2.0.9
  percent_indicator: ^4.2.2
  rename: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/poke_app_icon.png"
  adaptive_icon_foreground: "assets/icons/logo_foreground.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/gifs/
    - assets/images/
    - assets/animations/
